-- Deduping the transformed table by UNIQUE_ORDER_ID
CREATE OR REPLACE TABLE SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED(
                    ORDER_ID VARCHAR,
                    CUSTOMER_NAME VARCHAR,
                    MOBILE_BRAND VARCHAR,
                    MOBILE_MODEL VARCHAR,
                    MOBILE_COLOR VARCHAR,
                    MOBILE_RAM VARCHAR,
                    MOBILE_MEMORY VARCHAR,
                    QUANTITY VARCHAR,
                    PRICE_PER_UNIT_USD VARCHAR,
                    PROMOTION_CODE VARCHAR,
                    TOTAL_PRICE_USD VARCHAR,
                    ORDER_AMOUNT_USD VARCHAR,
                    TAX VARCHAR,
                    ORDER_DATE VARCHAR,
                    PAYMENT_STATUS VARCHAR,
                    SHIPPING_STATUS VARCHAR,
                    PAYMENT_METHOD VARCHAR,
                    PAYMENT_PROVIDER VARCHAR,
                    CONTACT_NUMBER VARCHAR,
                    COUNTRY VARCHAR,
                    DELIVERY_ADDRESS VARCHAR,
                    INSERT_DTS VARCHAR,
                    UNIQUE_ORDER_ID VARCHAR
                    );
                    
INSERT INTO SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED
WITH dedup AS(
    SELECT
        *,
        ROW_NUMBER() OVER(PARTITION BY UNIQUE_ORDER_ID ORDER BY UNIQUE_ORDER_ID) AS rn
    FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER
)
SELECT
    ORDER_ID VARCHAR,
                    CUSTOMER_NAME,
                    MOBILE_BRAND,
                    MOBILE_MODEL,
                    MOBILE_COLOR,
                    MOBILE_RAM,                    
                    MOBILE_MEMORY,               
                    QUANTITY,
                    PRICE_PER_UNIT_USD,
                    PROMOTION_CODE,
                    TOTAL_PRICE_USD,
                    ORDER_AMOUNT_USD,
                    TAX,ORDER_DATE,
                    PAYMENT_STATUS,
                    SHIPPING_STATUS,
                    PAYMENT_METHOD,
                    PAYMENT_PROVIDER,
                    CONTACT_NUMBER,
                    COUNTRY,
                    DELIVERY_ADDRESS,
                    INSERT_DTS,
                    UNIQUE_ORDER_ID
FROM dedup
    WHERE rn= 1;

-- Creating the dimension tables
-- DIM_PRODUCT
CREATE OR REPLACE TABLE SNOWPARK_DB.CURATED.DIM_PRODUCT(
        PRODUCT_KEY number autoincrement,
        MOBILE_BRAND VARCHAR,
        MOBILE_MODEL VARCHAR,
        MOBILE_COLOR VARCHAR,
        MOBILE_RAM VARCHAR,
        MOBILE_MEMORY VARCHAR
);

-- DIM_CUSTOMER
CREATE OR REPLACE TABLE SNOWPARK_DB.CURATED.DIM_CUSTOMER(
        CUSTOMER_KEY number autoincrement,
        CUSTOMER_NAME VARCHAR,
        CONTACT_NUMBER VARCHAR,
        COUNTRY VARCHAR
);

-- DIM_PAYMENT
CREATE OR REPLACE TABLE SNOWPARK_DB.CURATED.DIM_PAYMENT(
        PAYMENT_KEY number autoincrement,
        PAYMENT_METHOD VARCHAR,
        PAYMENT_PROVIDER VARCHAR
);

-- DIM_PROMOTION
CREATE OR REPLACE TABLE SNOWPARK_DB.CURATED.DIM_PROMOTION(
    PROMOTION_KEY number autoincrement,
    PROMOTION_CODE VARCHAR
);

-- FCT_SALES_ORDER
CREATE OR REPLACE TABLE SNOWPARK_DB.CURATED.FCT_SALES_ORDER(
        UNIQUE_ORDER_ID VARCHAR NOT NULL,
        ORDER_DATE VARCHAR,
        CUSTOMER_KEY NUMBER,
        PRODUCT_KEY NUMBER,
        PAYMENT_KEY NUMBER,
        PROMOTION_KEY NUMBER,

        QUANTITY NUMBER,
        PRICE_PER_UNIT NUMBER,
        TOTAL_PRICE NUMBER,
        ORDER_AMOUNT NUMBER,
        TAX NUMBER,

        PAYMENT_STATUS VARCHAR,
        SHIPPING_STATUS VARCHAR,
        DELIVERY_ADDRESS VARCHAR
);

-- Loading data into dimension tables
-- Load DIM_PRODUCT

MERGE INTO SNOWPARK_DB.CURATED.DIM_PRODUCT d
    USING(
            SELECT DISTINCT
                MOBILE_BRAND, MOBILE_MODEL, MOBILE_COLOR, MOBILE_RAM, MOBILE_MEMORY
            FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED
    ) s
        ON d.MOBILE_BRAND = s.MOBILE_BRAND
        and d.MOBILE_MODEL = s.MOBILE_MODEL
        and d.MOBILE_COLOR = s.MOBILE_COLOR
        and d.MOBILE_RAM = s.MOBILE_RAM
        and d.MOBILE_MEMORY = s.MOBILE_MEMORY
    WHEN NOT MATCHED THEN INSERT(
        MOBILE_BRAND, MOBILE_MODEL, MOBILE_COLOR, MOBILE_RAM, MOBILE_MEMORY
    ) VALUES (
        s.MOBILE_BRAND, s.MOBILE_MODEL, s.MOBILE_COLOR, s.MOBILE_RAM, s.MOBILE_MEMORY
    );

-- DIM_CUSTOMER

MERGE INTO SNOWPARK_DB.CURATED.DIM_CUSTOMER c
    USING(
            SELECT DISTINCT
                CUSTOMER_NAME, CONTACT_NUMBER, COUNTRY  
            FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED
    ) s
        ON c.CUSTOMER_NAME = s.CUSTOMER_NAME
        AND c.CONTACT_NUMBER = s.CONTACT_NUMBER
        AND c.COUNTRY = s.COUNTRY
    WHEN NOT MATCHED THEN INSERT(
        CUSTOMER_NAME, CONTACT_NUMBER, COUNTRY
    ) VALUES(
        s.CUSTOMER_NAME, s.CONTACT_NUMBER, s.COUNTRY
    );

-- DIM_PAYMENT
MERGE INTO SNOWPARK_DB.CURATED.DIM_PAYMENT p
    USING(
            SELECT DISTINCT
                PAYMENT_METHOD, PAYMENT_PROVIDER 
            FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED
    ) s
        ON p.PAYMENT_METHOD = s.PAYMENT_METHOD
        AND p.PAYMENT_PROVIDER  = s.PAYMENT_PROVIDER 
    WHEN NOT MATCHED THEN INSERT(
        PAYMENT_METHOD, PAYMENT_PROVIDER
    ) VALUES(
        s.PAYMENT_METHOD, s.PAYMENT_PROVIDER
    );
--DIM_PROMOTION
MERGE INTO SNOWPARK_DB.CURATED.DIM_PROMOTION p
    USING(
            SELECT DISTINCT
                PROMOTION_CODE 
            FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED
    ) s
        ON p.PROMOTION_CODE = s.PROMOTION_CODE
    WHEN NOT MATCHED THEN INSERT(
        PROMOTION_CODE
    ) VALUES(
        s.PROMOTION_CODE
    );

-- FCT_SALES_ORDER
INSERT INTO SNOWPARK_DB.CURATED.FCT_SALES_ORDER
SELECT
    g.UNIQUE_ORDER_ID,
    g.ORDER_DATE,
    c.CUSTOMER_KEY,
    p.PRODUCT_KEY,
    dp.PAYMENT_KEY,
    dpr.PROMOTION_KEY,
    g.QUANTITY,
    g.PRICE_PER_UNIT_USD,
    g.TOTAL_PRICE_USD,
    g.ORDER_AMOUNT_USD,
    g.TAX,
    g.PAYMENT_STATUS,
    g.SHIPPING_STATUS,
    g.DELIVERY_ADDRESS   
FROM SNOWPARK_DB.TRANSFORMED.GLOBAL_SALES_ORDER_DEDUPED AS g
    JOIN SNOWPARK_DB.CURATED.DIM_CUSTOMER AS c
        ON g.CUSTOMER_NAME = c.CUSTOMER_NAME
        AND g.CONTACT_NUMBER = c.CONTACT_NUMBER
        AND g.COUNTRY = c.COUNTRY
    JOIN SNOWPARK_DB.CURATED.DIM_PRODUCT AS p
        ON p.MOBILE_BRAND = g.MOBILE_BRAND
        and p.MOBILE_MODEL = g.MOBILE_MODEL
        and p.MOBILE_COLOR = g.MOBILE_COLOR
        and p.MOBILE_RAM = g.MOBILE_RAM
        and p.MOBILE_MEMORY = g.MOBILE_MEMORY
    JOIN SNOWPARK_DB.CURATED.DIM_PAYMENT AS dp
        ON dp.PAYMENT_METHOD = g.PAYMENT_METHOD
        AND dp.PAYMENT_PROVIDER  = g.PAYMENT_PROVIDER 
    JOIN SNOWPARK_DB.CURATED.DIM_PROMOTION AS dpr
        ON dpr.PROMOTION_CODE = g.PROMOTION_CODE;

SELECT * FROM SNOWPARK_DB.CURATED.FCT_SALES_ORDER;




