//Create the database
CREATE OR REPLACE DATABASE SNOWPARK_DB;

USE DATABASE SNOWPARK_DB;

// Create the schemas
CREATE OR REPLACE SCHEMA STAGING; -- schema to store the s3 data
CREATE OR REPLACE SCHEMA RAW; -- schema to store raw data
CREATE OR REPLACE SCHEMA TRANSFORMED; -- schema to store transformed data
CREATE OR REPLACE SCHEMA CURATED; -- schema to store aggregated data

// Set up Staging Schema with tables
USE SCHEMA SNOWPARK_DB.STAGING;

// Create the respective tables from s3
// India Sales Order Copy Table (CSV in S3)
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.INDIA_SALES_ORDER_CP
(
    ORDER_ID VARCHAR(1000),
    CUSTOMER_NAME VARCHAR(1000),
    MOBILE_MODEL VARCHAR(1000),
    QUANTITY VARCHAR(1000),
    PRICE_PER_UNIT VARCHAR(1000),
    TOTAL_PRICE VARCHAR(1000),
    PROMOTION_CODE VARCHAR(1000),
    ORDER_AMOUNT VARCHAR(1000),
    GST VARCHAR(1000),
    ORDER_DATE VARCHAR(1000),
    PAYMENT_STATUS VARCHAR(1000),
    SHIPPING_STATUS VARCHAR(1000),
    PAYMENT_METHOD VARCHAR(1000),
    PAYMENT_PROVIDER VARCHAR(1000),
    MOBILE VARCHAR(1000),
    DELIVERY_ADDRESS VARCHAR(1000)
);

// USA Sales Order Copy Table (Parquet in S3)
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.USA_SALE_ORDER_CP
(
    SOURCE_DATA VARIANT
);

// France Sales Order Copy Table (JSON in S3)
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.FRANCE_SALE_ORDER_CP
(
    SOURCE_DATA VARIANT
);

// Create a storage integration between Snowflake and S3
CREATE OR REPLACE STORAGE INTEGRATION SNOWPARK_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<ARN'> -- ARN in AWS
    STORAGE_ALLOWED_LOCATIONS = ('<s3_url>'); -- S3 Url

// Describe the storage integration
DESC INTEGRATION SNOWPARK_INT;

// Create External Stage
CREATE STAGE SNOWPARK_DB.STAGING.SNOWPARK_STAGE
STORAGE_INTEGRATION = SNOWPARK_INT
URL = '<s3-url>';

// Validate the setup of the stage
ls @SNOWPARK_DB.STAGING.SNOWPARK_STAGE;






